import { VideoIdentifiers } from "../lr/lr-types";

export const loTypes = ["note", "book", "archive", "web", "github", "panelnote", "paneltalk", "panelvideo", "talk", "unit", "side", "topic"];

export class Properties {
  [key: string]: string;
}

export interface IconType {
  type: string;
  color: string;
}

export interface LabStep {
  title: string;
  shortTitle: string;
  contentMd: string;
  contentHtml: string;
  route: string;
  id: string;
  type: string;
  hide: boolean;
  parentLo?: Lo;
  parentCourse?: Lo;
}

export interface Lo {
  type: string; // type of lo, one of loTypes above
  id: string; // folder name containing the lo
  title: string; // first line of markdown
  summary: string; // second three lines of markdown
  contentMd: string; // complete contents of markdown
  frontMatter: Properties; // frontmatter properties if present in markdown
  contentHtml?: string; // html generated by markdown conversion

  los: Array<Lo | LabStep>; // child los
  route: string; // url to the lo

  img: string; // url to the image for the lo
  imgFile: string; // the image file name
  icon?: IconType; // icon to be used of no image file found, extracteed from frontmatter in markdown

  pdf: string; // route to pdf for the lo
  pdfFile: string; // pdf file name

  archiveFile?: string; // archive file in the lo

  video: string; // video id
  videoids: VideoIdentifiers; // video name/value pairs if present

  hide: boolean; // hide flag, for ignore feature

  properties?: Properties; // contents of properties.yaml
  calendar?: Properties; // contents of calendar.yaml

  // dynamic properties, created by decorator
  parentLo?: Lo; // immediate parent lo
  parentCourse?: Lo; // parent course
  panels?: any; // child panel los - paneltalks, panelvideos, panelnotes.
  units?: any; // child units, including side units
  breadCrumbs?: Lo[]; // all los from course to this lo
}

export const preOrder = new Map([
  ["unit", 1],
  ["side", 2],
  ["talk", 3],
  ["lab", 4],
  ["note", 5],
  ["web", 6],
  ["github", 7],
  ["panelnote", 8],
  ["paneltalk", 9],
  ["archive", 10],
  ["panelvideo", 11],
  ["topic", 12],
  ["unknown", 13],
  ["", 0],
]);
