import { LearningResource, VideoIdentifiers } from "../builders/lo-types";
export declare function getFileWithName(lr: LearningResource, file: string): string;
export declare function getRoute(lr: LearningResource): string;
export declare function getFileWithType(lr: LearningResource, types: string[]): string;
export declare function getFilesWithType(lr: LearningResource, type: string): string[];
export declare function getFilesWithTypes(lr: LearningResource, types: string[]): string[];
export declare function getId(lr: LearningResource): string;
export declare function getImage(lr: LearningResource): string;
export declare function getArchive(lr: LearningResource): string;
export declare function getWebLink(lr: LearningResource): string;
export declare function getGitLink(lr: LearningResource): string;
export declare function getLabImage(lr: LearningResource): string;
export declare function getPdf(lr: LearningResource): string;
export declare function getVideo(lr: LearningResource, id: string): string;
export declare function getMarkdown(lr: LearningResource, keyFileName?: string): [string, string, string, any];
export declare function readVideoIds(lr: LearningResource): VideoIdentifiers;
export declare function readYaml(lr: LearningResource): any;
