export declare function writeFile(folder: string, filename: string, contents: string): void;
export declare function findFirstMatchingString(strings: string[], search: string, courseRoot: string): string;
export declare function findLastMatchingString(strings: string[], search: string): string;
export declare function getFileName(filePath: string): string;
export declare function getFileType(fileName: string): string;
export declare function readWholeFile(path: string): string;
export declare function readFirstLineFromFile(path: string): string;
export declare function getHeaderFromBody(body: string): string;
export declare function withoutHeaderFromBody(body: string): string;
export declare function copyFolder(src: string, dest: string): void;
export declare function copyFile(src: string, dest: string): void;
export declare function copyFileToFolder(src: string, dest: string): void;
export declare function readYamlFile(yamlFilePath: string): any;
